#!/usr/bin/env python3
#
# Simple PWM controller
# Remote control tool
#
# Copyright (c) 2018-2021 Michael Buesch <m@bues.ch>
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License along
# with this program; if not, write to the Free Software Foundation, Inc.,
# 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301 USA.
#

from libsimplepwm.gui import *
import argparse
import sys

def main():
    p = argparse.ArgumentParser(description="SimplePWM remote control")
    p.add_argument("port", nargs="?", type=str,
                   default=None,
                   help="Serial port.")
    args = p.parse_args()

    mainwnd = MainWindow(connectTo=args.port)
    mainwnd.show_all()
    Gtk.main()
    return 0

if __name__ == "__main__":
    sys.exit(main())

# vim: ts=4 sw=4 expandtab
