/* PWM setpoint to battery voltage drop transformation curve.
 * PWM setpoint range: 0 - 65535 (0xFFFF)
 * Battery drop range: 0 - 65535 (0xFFFF) mV
 * Curve generated by: battery_drop_curve.ods
 */
static const struct curve_point __flash sp2batdrop_curve[] = {
        CURVE_POINT(0, 0),
        CURVE_POINT(655, 130),
        CURVE_POINT(5243, 200),
        CURVE_POINT(32768, 290),
        CURVE_POINT(65535, 360),
};
