/* Raw ADC to PWM setpoint transformation curve.
 * ADC range:          0 - 1023 (0x3FF)
 * PWM setpoint range: 0 - 65535 (0xFFFF)
 * Curve generated by: brightness_curve.ods
 */
static const struct curve_point __flash adc2sp_transformation_curve[] = {
        /* raw ADC, PWM setpoint */
        CURVE_POINT(0, 0),
        CURVE_POINT(10, 0),
        CURVE_POINT(96, 551),
        CURVE_POINT(256, 2101),
        CURVE_POINT(416, 4981),
        CURVE_POINT(576, 10401),
        CURVE_POINT(716, 18804),
        CURVE_POINT(844, 31928),
        CURVE_POINT(940, 46867),
        CURVE_POINT(1013, 65535),
        CURVE_POINT(1023, 65535),
};

static const struct curve_point __flash adc2sp_transformation_linear[] = {
        /* raw ADC, PWM setpoint */
        CURVE_POINT(0, 0),
        CURVE_POINT(10, 0),
        CURVE_POINT(1013, 65535),
        CURVE_POINT(1023, 65535),
};
